### ISSUE TITLE
Categorise all available Calculators

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#10]
In side-navbar, Calculator Options are not properly categorised
![Screenshot_20210304-184803_Chrome](https://user-images.githubusercontent.com/60106112/109969834-5eeacd00-7d1a-11eb-990b-ed24dae9d941.jpg)

Categorise them with suitable Categories

Like under **General Maths** category:
there is
- Plot Graph

but it should be in other suitable category.

**Comment by haripriya9647** [comment]
Hey I would like to work on this issue but I need a little guidance.

**Comment by sairish2001** [comment]
Sorry! Since I already assigned you 2 issues, and you are currently working on it. Once you complete your either of any issue. I will assign you this also.

but in the meantime, if any other participant comes, I will assign to him/her.

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by sairish2001** [comment]
Deadline 13 March,2021(11:59 PM IST)

**Comment by Ankita297** [comment]
Sir i need some guidance like we need to make a different category for plot graph ? Example like category should be Graphs 
?

**Comment by Ankita297** [comment]
Because in Readme file plot graph is in general category .

**Comment by sairish2001** [comment]
Don't consider README.md 

Make Categories which suits by yourself

**Comment by sairish2001** [comment]
> Sir i need some guidance like we need to make a different category for plot graph ? Example like category should be Graphs
> ?

Yes you can

**Comment by Ankita297** [comment]
![Makes Math Easy - Google Chrome 12-03-2021 15_03_02](https://user-images.githubusercontent.com/67833077/110921056-1ea3d400-8344-11eb-8c7a-5431db716c62.png)
![Makes Math Easy - Google Chrome 12-03-2021 15_03_10](https://user-images.githubusercontent.com/67833077/110921061-206d9780-8344-11eb-9fe0-11a13c7c270c.png)

**Comment by Ankita297** [comment]
![Makes Math Easy - Google Chrome 12-03-2021 15_02_41](https://user-images.githubusercontent.com/67833077/110921137-35e2c180-8344-11eb-8f20-a4669266269a.png)
![Makes Math Easy - Google Chrome 12-03-2021 15_02_52](https://user-images.githubusercontent.com/67833077/110921145-37ac8500-8344-11eb-8993-f12c0ea20c05.png)

**Comment by Ankita297** [comment]
Sir is it okay ?

**Comment by sairish2001** [comment]
Do add **Play with Equations** function in **General Equations category**

Change **General Equations Category** name to **_Equations_**
