### ISSUE TITLE
enhancement in about section

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy.github.io#101]
## Proposal
The About section would look nicer in the center also can add a pointer cursor when a user hovers on it. 
(A clear and concise description of what the proposal is.)
![mi3](https://user-images.githubusercontent.com/61223163/110793386-90bfde80-829a-11eb-96ad-9d8eecc4532f.PNG)

**Comment by gnikita432** [comment]
can you please assign me this issue under GSSOC'21

**Comment by sairish2001** [comment]
If you want to add some documentation in the About Section, then you can as this project is now Open Source.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 13 March,2021 (11:59 PM IST)

**Comment by gnikita432** [comment]
Sure I will let you know my ideas for the about section.
