### ISSUE TITLE
Copyright text is overlapping the SideNav 

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#106]
![image](https://user-images.githubusercontent.com/60106112/110808313-dd5ee600-82a9-11eb-97e3-ed562aac695e.png)
It must be at the last of Sidenav, with smaller font-size

**Comment by khareyash05** [comment]
Can i have it a go?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 13 March,2021(11:59 PM IST)

**Comment by khareyash05** [comment]
I have solved the problem sending in 2 mins
