### ISSUE TITLE
The image for the right angled triangle has wrong labellings (specifically base)

### ISSUE THREAD

**Issue by aanchalrakheja** [sairish2001/makesmatheasy.github.io#108]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![image](https://user-images.githubusercontent.com/68388581/110820386-0d5fb680-82b5-11eb-8f25-7f76aac47335.png)

- If applicable, add screenshots to help explain your problem.

**Comment by aanchalrakheja** [comment]
i would like to correct the issue. Please assign it to me

**Comment by sairish2001** [comment]
Deadline 14 March,2021 (11:59 PM IST)
