### ISSUE TITLE
Fix Numbers API functionality

### ISSUE THREAD

**Issue by Avash027** [sairish2001/makesmatheasy.github.io#11]
The Numbers API which is supposed to show trivia is not functioning. I would like to fix the issue

**Comment by sairish2001** [comment]
Go ahead. Thanks for showing interest in this project.

**Comment by Avash027** [comment]
Just one doubt. Should I make a separate JS file to implement this or implement in the index file

**Comment by sairish2001** [comment]
implement in index.js

**Comment by Avash027** [comment]
Sir, the PR is merged so the issue is resolved?

**Comment by sairish2001** [comment]
Well Done!
CORS issue is resolved but API with **http://** protocol fails to load in **https://**

**Comment by sairish2001** [comment]
Do you have a solution for it?

**Comment by Avash027** [comment]
Sir, It looks like the  API is only available for http. It fails for https
