### ISSUE TITLE
Font size of copyright is too small

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy.github.io#110]
## **Describe the bug**

Font size of copyright is too small. 

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![mi4](https://user-images.githubusercontent.com/61223163/110823031-b3acbb80-82b7-11eb-9791-5921d2ca996b.PNG)

**Comment by sairish2001** [comment]
I don't want, to show any information other than the app's motive. Hence I recommend to make its size small
