### ISSUE TITLE
fix Unit convertor.

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy.github.io#111]
In unit convertor , while clicking on any option other than length, the top part is showing length for all option.

<img width="1132" alt="Screenshot 2021-03-11 at 10 23 09 PM" src="https://user-images.githubusercontent.com/34344234/110824343-f9b64f00-82b8-11eb-98d2-4befbaec2b39.png">

Here, I clicked on volume, it still showing length while it should show volume.

**Comment by janvi01** [comment]
I would like to work.

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 March,2021 (11:59 PM IST)
