### ISSUE TITLE
Add a Footer

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy.github.io#116]
## **Is your feature request related to a problem? Please describe.**

I would like to add a Footer at the bottom 
Somewhat like this
![Bootstrap-footer-by-Kate](https://user-images.githubusercontent.com/60147732/110882741-6573d880-8308-11eb-9949-a46f389c8325.jpg)

**Comment by sairish2001** [comment]
Actually it's a web app, so I don't want such footers to appear
