### ISSUE TITLE
Add Factorial and Permutations and Combinations of a Number(General Maths)

### ISSUE THREAD

**Issue by Krishan-2000** [sairish2001/makesmatheasy.github.io#117]
Can I add two more option in General Maths :

1)Calculate Factorial of  a Number.
2)Permutations and Combinations of a Number.

I want to work on this feature Please assign this to me @sairish2001.

#GsSOC'21

**Comment by sairish2001** [comment]
Great issue!
Feel free to ask your doubts, if any
Deadline 17 March,2021 (11:59 PM IST)

**Comment by Krishan-2000** [comment]
Thanks for assign me this issue I will surely do this.

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.
