### ISSUE TITLE
Calculator is Excepting answer of string input as well

### ISSUE THREAD

**Issue by LalitMishra1504** [sairish2001/makesmatheasy.github.io#118]
## **Describe the bug**

On writing string in input instead of showing invalid input it is showing the answer
#Gssoc'21 participant.
Sir please assign this to me @sairish2001 

## **Possible solution**

-I can use REGEX for not allowing alphabets

## **Screenshots**
![Screenshot (1026)](https://user-images.githubusercontent.com/78636179/110894957-d7efb300-831e-11eb-8b31-f030dc36f38e.png)

**Comment by sairish2001** [comment]
[#17](https://github.com/sairish2001/makesmatheasy.github.io/issues/17) issue is already open for the same

**Comment by LalitMishra1504** [comment]
ok sir
