### ISSUE TITLE
Finding Mean,Median,Mode of a numbers

### ISSUE THREAD

**Issue by LalitMishra1504** [sairish2001/makesmatheasy.github.io#120]
if a user input numbers and he/she will click on mean button to find mean click on median button to find median and mode button to find mode.
I am a gssoc'21 participant can you please assign me this @sairish2001

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 17 March,2021 (11:59 PM IST)

**Comment by LalitMishra1504** [comment]
Thanks for assigning this to me i will do my best

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.
