### ISSUE TITLE
Simple and Compound Interest

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy.github.io#125]
Can I add a feature of finding simple and compound interest

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 17 March,2021 (11:59 PM IST)

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by khareyash05** [comment]
Sorry @rk05-lenavo I am already working on this issue

**Comment by khareyash05** [comment]
@sairish2001 Creating a new PR give me 2 mins
