### ISSUE TITLE
[GSSoC '21] Binary Converter

### ISSUE THREAD

**Issue by amrzaki2000** [sairish2001/makesmatheasy.github.io#128]
Hello,
I'd like to work on a feature that shows how to convert decimal numbers to binary numbers.
I'm a GSSoC participant.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any
Deadline 17 March,2021 (11:59 PM IST)

**Comment by amrzaki2000** [comment]
> 
> 
> Feel Free to ask your doubts, if any
> Deadline 17 March,2021 (11:59 PM IST)

Should I create a new list element for binary system or just add the feature to 'Basic Converters' section?
I mean in case there is going to be any more binary calculations

**Comment by sairish2001** [comment]
Add in Basic Converters section

**Comment by amrzaki2000** [comment]
> 
> 
> Make a new Category for Binary Numbers
> and Add there

Okay
Can I add more features or should I only create it then submit a new issue ?

**Comment by sairish2001** [comment]
Create this then Publish new issues, it's your choice if want to create issue, then go ahead

**Comment by amrzaki2000** [comment]
> 
> 
> Create this then Publish new issues, it's your choice if want to create issue, then go ahead

Okay, thanks

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
