### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [sairish2001/makesmatheasy.github.io#131]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any
Deadline 16 March,2021 (11:59 PM IST)

**Comment by rohank2502** [comment]
> 
> 
> Feel Free to ask your doubts, if any
> Deadline 16 March,2021 (11:59 PM IST)

Ok Thanks !!

**Comment by rohank2502** [comment]
> 
> 
> Feel Free to ask your doubts, if any
> Deadline 16 March,2021 (11:59 PM IST)

Please give a review to PR I will do suggested changes !!
