### ISSUE TITLE
Add trigonometric identities.

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy.github.io#136]
Add separate trigonometric identities folder in trigonometry part.

somewhat like this
![TI](https://user-images.githubusercontent.com/34344234/111022066-7c90f400-83f6-11eb-89d5-df166c66e441.png)

**Comment by janvi01** [comment]
I would like to work.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any
Deadline 18 March,2021 (11:59 PM IST)
