### ISSUE TITLE
Adding animation to the "favourite" panel.

### ISSUE THREAD

**Issue by anu-cn** [sairish2001/makesmatheasy.github.io#139]
Hello sir, I am a GSSOC'21 participant. 
I would like to add animation to the "favourite" panel that is displayed at the bottom of the page, so that it can look more responsive while hovering over it.

**Comment by shrey27tri01** [comment]
@anu-cn We are planning to change the UI for the Favorites section, so we can't go ahead with this issue right now. But if you have any other ideas on how to improve the UI for the Favorites section, please feel free to create a new issue and we can assign that to you :smile:
