### ISSUE TITLE
Missing height label in image

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#147]
Label for height is missing in Scalene Triangle image
![scalene](https://user-images.githubusercontent.com/60106112/111041009-1474f900-845c-11eb-9d8f-d1fea6518a3e.png)

**Comment by madihamallick** [comment]
@sairish2001 I would like to add the feature please assign this issue to me under gssoc21

**Comment by deek121477** [comment]
I would like to work on this issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 16 March,2021 (11:59 PM IST)
