### ISSUE TITLE
checking sides of valid triangle

### ISSUE THREAD

**Issue by ainy-123** [sairish2001/makesmatheasy.github.io#151]
I would like to add a feature to this project that, given 3 numbers ,output whether they can be the sides of a triangle or not?

I am a GSSoC'21 participant and want to work on this feature .Please assign it to me.

**Comment by sairish2001** [comment]
Under which category you will add this feature?

**Comment by ainy-123** [comment]
We can create a section of 'geometry' like the trigonometry, calculus etc and then can add this issue in that category and there can be many issues created in this category which will make maths more easy,like we can implement various geometry formulas,like finding area of the triangle ,if the sides are valid ,and so on.

> Under which category you will add this feature?

We can create a section of 'geometry' like the trigonometry, calculus etc and then can add this issue in that category and there can be many issues created in this category which will make maths more easy,like we can implement various geometry formulas,like finding area of the triangle ,if the sides are valid ,and so on.

**Comment by sairish2001** [comment]
Calculating areas, volums ,etc are already implemented in Shapes Calculator under Shapes and Graph Category you can check it out.

**Comment by ainy-123** [comment]
Ok thank you . should I close this issue then?

> Calculating areas, volums ,etc are already implemented in Shapes Calculator under Shapes and Graph Category you can check it out.
