### ISSUE TITLE
Scroll bar at the end of the page

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy.github.io#156]
The scroll bar can be improved upon. As of now it is not covering the entire width of the left side of page.

Reference screenshot:
![image](https://user-images.githubusercontent.com/56315878/111065451-c570a780-84df-11eb-875f-b648e113781d.png)

Would like to work on it under GSSOC' 21.
Thanks!

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by shrey27tri01** [comment]
@satcasm you can work on this issue :) 
Feel free to ask any doubts!
Deadline: 20 March, 2021 (11:59 PM IST)

Also, @Ayushbajpai19 you can look for other issues, or explore the codebase and find out bugs or features to add :smile:
