### ISSUE TITLE
Conversion from Radian to Degree in Calculator

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#16]
Apply Working to Degree converter
![PicsArt_03-06-05 03 05](https://user-images.githubusercontent.com/60106112/110205451-f593c700-7e9d-11eb-85af-6e2fb5e3eedc.png)

Till now Default Answer is in Radians, I want to Convert it in Degree on clicking the DEG button

Working:
- Click DEG button 
- DEG text changes to RAD
- fetch data from input field `document.getElementById('txt');`  having id="txt"
- Run the Radian to Degree conversion code
- Display Answer in solution field `document.getElementById('soltext');` having id="soltext"
- Thats all
- Calculator's logic is in [simplecallogic.js](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/appjs/simplecallogic.js) file
```
if(document.getElementById('percent').innerText=="RAD"){
       Run Degree to Radian conversion code 
       document.getElementById("percent").innerText="DEG";
}else{     
      Run Radian to Degree conversion code
      document.getElementById("percent").innerText="RAD";
}
```
Point to be noted!
- Radian to Degree converter and vice-versa must be a toggle button

**Comment by satyampgt4** [comment]
I would like to work on this issue as a part of GSSOC 2021 and I will make a PR for this when the contribution period starts.

**Comment by sairish2001** [comment]
Thanks for showing interest in this Project.
Feel free to ask your doubts if any.

**Comment by sairish2001** [comment]
Hey! @satyampgt4
I have updated the Issue, kindly read once again.
Actually the Answer is in Radians we have to convert it in Degrees. 
Sorry for inconvenience.

**Comment by satyampgt4** [comment]
to get answer in Degrees.
i  try using following code
```
document.getElementById('seven').addEventListener("click", function() {

document.getElementById('txt').value+=this.innerText;
	calsol(document.getElementById('txt').value);

if(document.getElementById('seven').innerText !="7" && document.getElementById('percent').innerText=="RAD"){
      document.getElementById('txt').value+=(pi/180)*;
	calsol(document.getElementById('txt').value);   
	
});
```
for all element like zero, one, two ...nine 

to do i also need to remove all inline onclick call in index.html like -

```
<span id="seven" onclick="document.getElementById('txt').value+=this.innerText;calsol(document.getElementById('txt').value);">sin(</span>

//to

<span id="seven">sin(</span>
```


so should i procede or you have any other suggetion to do so @sairish2001

**Comment by sairish2001** [comment]
This will hinder the all functionality, i will suggest you something

**Comment by sairish2001** [comment]
Is your code is working fine?

**Comment by sairish2001** [comment]
Go ahead with your code!

**Comment by satyampgt4** [comment]
> Is your code is working fine?

yes it is working

**Comment by sairish2001** [comment]
Will your work be done by tomorrow?

**Comment by satyampgt4** [comment]
it is already done i just waiting once gsoc coding period officially start to make pull request

**Comment by sairish2001** [comment]
Go ahead with PR, GSSOC'21 periods starts.

**Comment by sairish2001** [comment]
Well Done, Great Work!
Thanks for your contribution.
