### ISSUE TITLE
Complex number calculation

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy.github.io#161]
I would like to add basic operations on complex numbers under GSSOC' 21.
Thanks!

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

Deadline 19 March,2021 (11:59 PM IST)

**Comment by satcasm** [comment]
Hey @sairish2001 I was wondering whether I should write a code for a complex number calculator or add it in like as a separate option?
I am planning on doing something like this:
![image](https://user-images.githubusercontent.com/56315878/111293887-c20c2600-866f-11eb-9858-ea35c3ebb455.png)

**Comment by sairish2001** [comment]
Add a single option which serves the purpose for all

**Comment by satcasm** [comment]
@sairish2001 can you please have a look as to why the ```complexcollapse``` is not working? I tried debugging it for a while and I got nowhere , it's a pretty basic mistake somewhere but still I am not getting it.
Much appreciated!

This is the code for the ```<li>```:

![image](https://user-images.githubusercontent.com/56315878/111330370-dfec8180-8695-11eb-9888-82baa3dcacc5.png)

This is the code for the ```complexcollapse```:

![image](https://user-images.githubusercontent.com/56315878/111330598-17f3c480-8696-11eb-9dad-7ce470a0300d.png)

When I click on ```Calculations``` nothing is getting rendered.

**Comment by sairish2001** [comment]
You are trying to say collapse, It's not collapsing?

**Comment by satcasm** [comment]
yeah , I mean I tried doing something similar to other options. I saw that we have to  first define a ```li``` tag and then a div with ```collapse``` class where the main operation is performed.

**Comment by sairish2001** [comment]
What Problem you are facing?
It's not opening on button click?

**Comment by satcasm** [comment]
Yeah

**Comment by sairish2001** [comment]
You need to add id `#complexcollapse` in `function openit()` in index.js file

**Comment by sairish2001** [comment]
also to call openit() function check out `working.js` file

**Comment by satcasm** [comment]
Thanks man you are a life savor, I should have checked other files was stuck on it for the whole day!
