### ISSUE TITLE
LIMITS under calculus

### ISSUE THREAD

**Issue by Drishtdyumnss** [sairish2001/makesmatheasy.github.io#164]
I want to add all the limit formulas under calculus section . 
@sairish2001 please assign this feature to me under GSSOC21.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any
Deadline 19 March,2021(11:59 PM IST)

**Comment by Drishtdyumnss** [comment]
[{sin\space\theta}{cos\space\theta}\] 
what is this syntax called... i want to read more about this

**Comment by sairish2001** [comment]
This is basically LaTex text

**Comment by Drishtdyumnss** [comment]
under which section does it comes ....cs i find this often used in both html and js
can u provide me link to further explore this laTex

**Comment by Drishtdyumnss** [comment]
@sairish2001 
how to write superscript and subscript using LaTex syntax in html
can u give one example
