### ISSUE TITLE
False Voice inputs in Calculator

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#17]
Calculator must allow only inputs containing integers,some arithmetic operations, and some special functions like (sin(), cos(),....etc)

---

For more clarification see video👇🏻

https://user-images.githubusercontent.com/60106112/110197352-13970280-7e71-11eb-893b-8d0435c6fa17.mp4

---

Solution:
You can use REGEX( Regular Expressions) for not allowing alphabets.
Special Case for:
![Screenshot_20210306-114728_Makes Math Easy](https://user-images.githubusercontent.com/60106112/110197474-c10a1600-7e71-11eb-83b6-99d2b983da2d.jpg)
- sin
- cos
- asin
- e( exponential )
- log
- many more, shown in picture

---

Logic for Speech recognition is in [speechreco.js](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/appjs/speechreco.js) file

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by Sukriti-sood** [comment]
@sairish2001  Can you assign this to me.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any

**Comment by sairish2001** [comment]
Deadline 13 March,2021(11:59 PM IST)

**Comment by sairish2001** [comment]
Deadline is near @Sukriti-sood any update?

**Comment by Sukriti-sood** [comment]
> Deadline is near @Sukriti-sood any update?

Sorry Sir due to some reason I was not able to do anything, I will try from my side in the time left.

**Comment by Sukriti-sood** [comment]
@sairish2001  For invalid Expression, what calculator need to render,I mean will it give alert for invalid expression or will show no change n input?

**Comment by sairish2001** [comment]
no change

**Comment by Sukriti-sood** [comment]
@sairish2001 Please check The PR.
