### ISSUE TITLE
Interest calculator

### ISSUE THREAD

**Issue by satyampgt4** [sairish2001/makesmatheasy.github.io#171]
## Proposal

A calculator for calculating simple and compound interest

**Comment by satyampgt4** [comment]
I would like to work on this issue @sairish2001 under gssoc 2021

**Comment by sairish2001** [comment]
Feel free to ask your doubt, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by khareyash05** [comment]
@sairish2001 To bring to your notice I had already created an interest calculator before . This has created a duplicate .
