### ISSUE TITLE
Adding Octal to Binary Conversion and Viceversa option 

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy.github.io#172]
## **Is your feature request related to a problem? Please describe.**

Presently,there is only option of conversion of binary to decimal and viceversa why not include other bases .

## **Describe the solution you'd like**

I would like to add feauter of conversion of octal based number to binary and viceversa

**Comment by zhcet19** [comment]
I would like to work on this issue @sairish2001 under gssoc 2021

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)
