### ISSUE TITLE
Adding hexadecimel and octal based number in bitwise calculator

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy.github.io#178]
## **Is your feature request related to a problem? Please describe.**

Presently,only decimal and binary base is present why not include all other bases .

## **Describe the solution you'd like**

I want to add hexadecimal  and octal base also in this calculator

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
The issue is already opened for the same

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)
