### ISSUE TITLE
Add log() and log10() to Calculator

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#18]
![Picture](https://user-images.githubusercontent.com/60106112/110212353-f9851080-7ec0-11eb-9691-d31a652f3db6.png)

---

Just Change the text of these two buttons when the user clicks on **More**
Refer to [`function more(){}`](https://github.com/sairish2001/makesmatheasy.github.io/blob/8fceba522f4b351926fc871c132ba18e7f835eb5/appjs/simplecallogic.js#L61) in [simplecallogic.js](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/appjs/simplecallogic.js) file

Keep in mind!
The **More** button is a Toggle button so on toggle it must revert text to original i.e 
- **log(**  ->  **.**
- **log10(**  ->  **√**

**Comment by vmk8826** [comment]
can you please give id of sqrt

**Comment by vmk8826** [comment]
Done

**Comment by sairish2001** [comment]
You can add id to sqrt button by yourself

**Comment by vmk8826** [comment]
Done

**Comment by vmk8826** [comment]
it is working now

**Comment by sairish2001** [comment]
Can I assign this issue to you?

**Comment by vmk8826** [comment]
yes

**Comment by vmk8826** [comment]
How do I upload the code
I am new to this

**Comment by vmk8826** [comment]
![converted github](https://user-images.githubusercontent.com/68069180/110217857-7a053a80-7edc-11eb-9cb9-6de11db761de.png)

**Comment by vmk8826** [comment]
this is what you wanted right

**Comment by sairish2001** [comment]
Yes! exactly
When you click **More** button will it's content change back to √ and . ?

**Comment by sairish2001** [comment]
Be make sure when user clicks **√** it must display **sqrt(** not **√** on input field

**Comment by sairish2001** [comment]
- fork this repository 
- clone it in your local repository
- make changes to code
- make a commit to forked repository
- from forked repository make a PR with appropriate Message and Title

**Comment by vmk8826** [comment]
I have created a pull request
Did you get it

**Comment by sairish2001** [comment]
Well Done!
Thanks for your contribution.
Congratulations! your PR has been merged
