### ISSUE TITLE
Makes Math Easy Documentation for Linear Algebra

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#180]
Create a Documentation in github jekyll theme, telling briefly about how the Linear Algebra section works

Make a PR in [Documentation Repository](https://github.com/sairish2001/Makes-Math-Easy-Documentation)

**Comment by robin025** [comment]
hey @sairish2001 I would like to work on this issue as a GSSOC 21 participant

**Comment by sairish2001** [comment]
Deadline 20 March,2021(11:59 PM IST)
