### ISSUE TITLE
Create Documentation for Calculus and Trigonometry

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#181]
Create Documentation in github jekyll theme

[Documentation Repository](https://github.com/sairish2001/Makes-Math-Easy-Documentation)

**Comment by robin025** [comment]
hey @sairish2001 I would like to work on this issue as a GSSOC 21 participant and will provide all the info related to trigonometry along with all the necessary formulas and info
Kindly assign me this issue, I shall be very thankful to you

**Comment by sairish2001** [comment]
Go ahead Deadline 20 March,2021 (11:59 PM IST)
