### ISSUE TITLE
Add CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by rajeshpanjiyar** [sairish2001/makesmatheasy.github.io#182]
Adding contributor's name automatically. I request you to assign me so that I can start working on this.
And I am a participant under GSSoC'21

**Comment by sairish2001** [comment]
Contributors.md file is already there

**Comment by rajeshpanjiyar** [comment]
Sorry I didn't find it there. In which file is it?

**Comment by sairish2001** [comment]
It's Contributing.md 

The contributors section is already implemented in readme.md

**Comment by rajeshpanjiyar** [comment]
Okay You can close this.
