### ISSUE TITLE
light mode

### ISSUE THREAD

**Issue by Shubhrima** [sairish2001/makesmatheasy.github.io#186]
## **Is your feature request related to a problem? Please describe.**

Different themes evoke different emotions. This project has only one kind of view.

## **Describe the solution you'd like**
I want to add a light mode view to it.

- A clear and concise description of what you want to happen.
[change mode.docx](https://github.com/sairish2001/makesmatheasy.github.io/files/6143034/change.mode.docx)

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)
