### ISSUE TITLE
Missing height label in image

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy.github.io#192]
I guess it would be better to add the height label here too.

![Capture](https://user-images.githubusercontent.com/70858557/111222225-8dfa1c00-8601-11eb-8aba-a2abb1cf0b9a.PNG)

@sairish2001 I would like to add the feature please assign this issue to me under gssoc21

**Comment by shrey27tri01** [comment]
@madihamallick You can go ahead with the issue :)

Deadline: March 19, 2021, 11:59 PM IST
