### ISSUE TITLE
Extra currency convertor under "Binary Calculations"

### ISSUE THREAD

**Issue by zhcet19** [sairish2001/makesmatheasy.github.io#195]
## **Describe the bug**

No event has been attached on clicking currency convertor section
## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by shrey27tri01** [comment]
@zhcet19 Is this the one you're talking about? We already have a currency converter :)

![Screenshot from 2021-03-16 10-51-28](https://user-images.githubusercontent.com/52366674/111259883-d76c5a80-8645-11eb-8a43-6d005e636551.png)

**Comment by zhcet19** [comment]
![gssoc7](https://user-images.githubusercontent.com/55043876/111260244-7b560600-8646-11eb-880e-390f44e9295b.png)

**Comment by zhcet19** [comment]
@shrey27tri01 there is another one under binary calculation that is not working properly

**Comment by shrey27tri01** [comment]
Oh! My bad. That is actually a bug. We need to remove that currency converter option from under "Binary Calculations", since we already have a currency converter under "Basic Converters". You can go ahead and remove that if you want :)

**Comment by zhcet19** [comment]
Similarly there is an intereset calculator which is already under "General Maths".So can I remove both of them from "Binary Calculations " tag.

**Comment by shrey27tri01** [comment]
You can leave the interest calculator as of now, we can create a separate issue for that. For now, you can just go ahead with the currency converter issue :)
