### ISSUE TITLE
I would like to add "Bit Manipulation" (like OR , AND , XOR ) functionality 

### ISSUE THREAD

**Issue by Raj142** [sairish2001/makesmatheasy.github.io#199]
please assign it to me. i am participant of GSSoc'21 .

**Comment by Raj142** [comment]
Please assign it to me . i am a participant of GSSoC'21.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 21 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
This function is already there in our webapp
![image](https://user-images.githubusercontent.com/60106112/111311108-d3f7c400-8683-11eb-8b9d-a9bf92665fc5.png)
