### ISSUE TITLE
Reduce size of Materialize.min.js file

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#2]
**[Link to file](
https://www.github.com/sairish2001/makesmatheasy.github.io/tree/main/js%2Fmaterialize.min.js)**

Question!
Why and How I can reduce the size of file?
- I am using this file only for implementing SIDENAV provided by **Materialize**
- Rest of the functions I don't need in `materialize.min.js`
- Delete all Code other than SideNav's functionality

**Comment by Subhangini** [comment]
I want to work on this issue .

**Comment by sairish2001** [comment]
Thanks for showing interest in this Project.

**Comment by Subhangini** [comment]
Thank you for assigning me .I am a beginner and I saw the  file and was not able to understand that huge code  but according to your instructions  I think that i have  to delete all other codes except  those containing ` sidenav ` right?

**Comment by sairish2001** [comment]
yeah!
I understand, code is not readable.
don't worry delete and check(hit and try) may work.

Tip!
Delete a code,
check sidenav's functionality not hindered.

**Comment by sairish2001** [comment]
be make sure, sidenav's functionality not hindered,
check before making PR

**Comment by Subhangini** [comment]
ok 👍

**Comment by sairish2001** [comment]
you have to look only into [materialize.min.js](https://www.github.com/sairish2001/makesmatheasy.github.io/tree/main/js%2Fmaterialize.min.js) file

don't remove any code from any other file other than it.

**Comment by sairish2001** [comment]
Any Update? @Subhangini

**Comment by Subhangini** [comment]
> you have to look only into [materialize.min.js](https://www.github.com/sairish2001/makesmatheasy.github.io/tree/main/js%2Fmaterialize.min.js) file
> 
> don't remove any code from any other file other than it.

ok

**Comment by Subhangini** [comment]
> Any Update? @Subhangini

Working on it

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by Subhangini** [comment]
ok, I was not aware of this .

**Comment by Subhangini** [comment]
@sairish2001  the code inside materialize.min.js file is not related to functionality of any other operation except sidenav right?
Like matrix functionality will not get affected through the codes of this file right?

**Comment by Subhangini** [comment]
ok

**Comment by sairish2001** [comment]
Deadline 11 March,2021 (11:59 PM)
