### ISSUE TITLE
I would like to add "Prime numbers" functionality 

### ISSUE THREAD

**Issue by Raj142** [sairish2001/makesmatheasy.github.io#208]
- it takes a number N as input and return all the prime numbers from 1 to N.
Example : input = 10 ;
     answer = 2, 3, 5, 7

**Comment by Raj142** [comment]
please assign it me . i am participant of GSSoC'21.

**Comment by shrey27tri01** [comment]
@Raj142 You can go ahead with the issue :)

Please feel free to ask any doubts!
Deadline: 21 March, 2021, 11:59 PM IST

**Comment by sairish2001** [comment]
[issue #123](https://github.com/sairish2001/makesmatheasy.github.io/issues/123) already opened for the same
