### ISSUE TITLE
Fix the position of search bar

### ISSUE THREAD

**Issue by garvitgupta13** [sairish2001/makesmatheasy.github.io#212]
## **Describe the bug**

- Currently, the search bar is inconsistent. Please see the screenshot for clear understanding of this issue.

## **Possible solution**

-Change the position of search bar 

## **Screenshots**

![image](https://user-images.githubusercontent.com/70805691/111371003-e17e6f80-86be-11eb-842e-66afa0257285.png)

Please assign me this issue under gssoc21

**Comment by Raj142** [comment]
please assign it to me . i am a participant of GSSoC'21

**Comment by sairish2001** [comment]
[issue #205](https://github.com/sairish2001/makesmatheasy.github.io/issues/205) is already opened for the same
