### ISSUE TITLE
Adding volume calculator of shapes like cube, cuboid, cylinder, cone in section graphs and shapes

### ISSUE THREAD

**Issue by ShrutiOmer** [sairish2001/makesmatheasy.github.io#214]
## **Is your feature request related to a problem? Please describe.**

- I want to add volume calculator of 3-D shapes in the calculator for shapes section

## **Describe the solution you'd like**

- I will add shapes like cuboid, cube, cylinder, cone in the "calculator for shapes" and that will calculate the volume of the shapes.

I am a GSSOC participant ,please assign this issue to me

**Comment by sairish2001** [comment]
[issue #83](https://github.com/sairish2001/makesmatheasy.github.io/issues/83) is already opened for the same
