### ISSUE TITLE
Add Steps of Solving Roundoff

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#22]
[function Roundoff Calculator](https://github.com/sairish2001/makesmatheasy.github.io/blob/bc21219c8c6a8c6f6746217e646fe1cef8f901f1/appjs/logicjavascript.js#L1656)

Try to understand the code and show steps of what we are doing

---
**Example:**

Input Number: **6473**

Place of Roundoff: **Hundred**

<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>6</td>
      <td>4</td>
      <td>7</td>
      <td>3</td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td></td>
      <td>4</td>
      <td>7</td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>7>5</td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td></td>
      <td>4+1</td>
      <td></td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td></td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>6</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
</table>

**6473** after rounding off to nearest **Hundred** is **6500**

---

Special Case:

**Example:**

Input Number: **6473**

Place of Roundoff: **Ten Thousand**

<table>
    <tr>
      <th>Ten Thousand</th>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>0</td>
      <td>6</td>
      <td>4</td>
      <td>7</td>
      <td>3</td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Ten Thousand</th>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>0</td>
      <td>6</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Ten Thousand</th>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>0</td>
      <td>6>5</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Ten Thousand</th>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>0+1</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
</table>
<br>
<table>
    <tr>
      <th>Ten Thousand</th>
      <th>Thousand</th>
      <th>Hundred</th>
      <th>Tens</th>
      <th>Ones</th>
    </tr>
    <tr>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
</table>

**6473** after rounding off to nearest **Ten Thousand** is **10000**

**Comment by haripriya9647** [comment]
Hey can you assign me??

**Comment by sairish2001** [comment]
Feel free to ask doubts, if any.

Can you please tell are you a GSSOC'21 participant?

**Comment by haripriya9647** [comment]
Yes I am GSSOC21 participant.

**Comment by Abhisheka394** [comment]
Hi, I would like to work on this issue can you please assign it to me . I'm a GSsoc21 participant.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts,if any

**Comment by sairish2001** [comment]
Deadline 14 March,2021(11:59 PM IST)

**Comment by sairish2001** [comment]
@Abhisheka394 Any update? are you able to solve this.
There are some changes in our code kindly, update in your local machine

**Comment by Abhisheka394** [comment]
@sairish2001 I have started working on the task and I think I would be able to finish it on time. In case, I have some doubts I will ask you.

**Comment by sairish2001** [comment]
There are some changes in the code kindly, update in your local machine, otherwise while creating PR conflicts may occur

**Comment by sairish2001** [comment]
@Abhisheka394 Any update?
