### ISSUE TITLE
Additional features in complex calculations

### ISSUE THREAD

**Issue by satcasm** [sairish2001/makesmatheasy.github.io#225]
Hey @sairish2001 was thinking about adding some additional features in complex calculations , namely:
Absolute value, Square root, complex exponentiation and also giving the Division option as a part of GSSOC' 21.
Thanks!

**Comment by sairish2001** [comment]
Great👍

Go ahead
Feel free to ask your doubts, if any
Deadline 23 March,2021 (11:59 PM IST)
