### ISSUE TITLE
Create Calculator to Roundoff decimal numbers

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#23]
Create a calculator which Calculates Roundoff of a decimal number and implement it in [function roundoff()](https://github.com/sairish2001/makesmatheasy.github.io/blob/bc21219c8c6a8c6f6746217e646fe1cef8f901f1/appjs/logicjavascript.js#L1656)
you can check the condition that
```
if(number is float){
    design your code to roundoff a decimal  number 
}else{
    run the code which is already implemented
}
```

Till now [function roundoff()](https://github.com/sairish2001/makesmatheasy.github.io/blob/bc21219c8c6a8c6f6746217e646fe1cef8f901f1/appjs/logicjavascript.js#L1656) calculates Roundoff of only integer number.

Keep in mind!
Design a logic in that way so that we can easily show the steps for what we are doing. For more clarity you can check the code for [roundoff()](https://github.com/sairish2001/makesmatheasy.github.io/blob/bc21219c8c6a8c6f6746217e646fe1cef8f901f1/appjs/logicjavascript.js#L1656) which Calculates roundoff of non decimal number(integer)

**Comment by DEEPALI-SUK** [comment]
I want to work on this issue and want to contribute to this.I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by DEEPALI-SUK** [comment]
Could you please tell me whether the function needs to be completed or we have to design a calculator?

**Comment by sairish2001** [comment]
No No, just complete a function.

**Comment by DEEPALI-SUK** [comment]
I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any

**Comment by DEEPALI-SUK** [comment]
Ok and please could you tell me the deadline for this?

**Comment by sairish2001** [comment]
Take your time, I will ask you for the update after 3 days.

In the meantime, if any other participant comes and wants to work on this issue, I will ask you for the update before assigning him/her.

**Comment by sairish2001** [comment]
Don't use any inbuilt function to roundoff

Design your own code.
If wants a Hint how to design logic, feel free to ask.

**Comment by DEEPALI-SUK** [comment]
Ok sir.

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by DEEPALI-SUK** [comment]
Sir, please could you tell me what will be the output of 1245.3369, if we round it to tens place, 1245.3370 or 1250?

**Comment by DEEPALI-SUK** [comment]
Ones place in this example 1245.3369 is 9 or 5?

**Comment by sairish2001** [comment]
<table>
<tr>
<td>Thousand</td>
<td>Hundred</td>
<td>Tens</td>
<td>Ones</td>
<td></td>
<td>Ones</td>
<td>Tens</td>
<td>Hundred</td>
<td>Thousand</td>
</tr>
<td>1</td>
<td>2</td>
<td>4</td>
<td>5</td>
<td>.</td>
<td>3</td>
<td>3</td>
<td>6</td>
<td>9</td>
<tr>
</tr>
</table>

When round off to Tens Place
<table>
<tr>
<td>Thousand</td>
<td>Hundred</td>
<td>Tens</td>
<td>Ones</td>
<td></td>
<td>Ones</td>
<td>Tens</td>
<td>Hundred</td>
<td>Thousand</td>
</tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td>.</td>
<td>3</td>
<td>3</td>
<td></td>
<td></td>
<tr>
</tr>
</table>

Number at Ones place is smaller than 5
<table>
<tr>
<td>Thousand</td>
<td>Hundred</td>
<td>Tens</td>
<td>Ones</td>
<td></td>
<td>Ones</td>
<td>Tens</td>
<td>Hundred</td>
<td>Thousand</td>
</tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td>.</td>
<td>3<5</td>
<td>3</td>
<td></td>
<td></td>
<tr>
</tr>
</table>

<table>
<tr>
<td>Thousand</td>
<td>Hundred</td>
<td>Tens</td>
<td>Ones</td>
<td></td>
<td>Ones</td>
<td>Tens</td>
<td>Hundred</td>
<td>Thousand</td>
</tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td>.</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<tr>
</tr>
</table>

<table>
<tr>
<td>Thousand</td>
<td>Hundred</td>
<td>Tens</td>
<td>Ones</td>
<td></td>
<td>Ones</td>
<td>Tens</td>
<td>Hundred</td>
<td>Thousand</td>
</tr>
<td>1</td>
<td>2</td>
<td>4</td>
<td>5</td>
<td>.</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<tr>
</tr>
</table>

Answer: 1245.3

**Comment by DEEPALI-SUK** [comment]
![WhatsApp Image 2021-03-09 at 16 02 58](https://user-images.githubusercontent.com/64724041/110457817-1011ae80-80f1-11eb-9054-c54455f68e49.jpeg)
Sir here only one once is given and according to the above table there are two ones so can I add more options in the frontend?

**Comment by sairish2001** [comment]
No, need to add more options as our must view/change only those numbers which are on right side of decimal.

If you are confused a little bit. I would suggest you to see a video on how to Roundoff.

There's a spelling mistake
Correct:**Ones**
Wrong: **Once**

If you correct this also, in the JSON and Frontend, then I would appreciate.

**Comment by DEEPALI-SUK** [comment]
Ok sir

**Comment by DEEPALI-SUK** [comment]
Sir kindly review my work.
**1) When rounded to ones place.**

![ones place](https://user-images.githubusercontent.com/64724041/110479542-88856900-810b-11eb-9017-5a0a247c1c53.jpeg)


**2)When rounded to ones place.**

![ones place1](https://user-images.githubusercontent.com/64724041/110479715-b7034400-810b-11eb-86f0-360eb4f64627.jpeg)


**3)When rounded to tens place.**

![tens place](https://user-images.githubusercontent.com/64724041/110479862-dc904d80-810b-11eb-855a-7988aa0e714b.jpeg)


**4)When rounded to ones place.**

![ones place2](https://user-images.githubusercontent.com/64724041/110479967-f5006800-810b-11eb-8c14-065c69437621.jpeg)

**5)When rounded to thousands place.**

![thousand](https://user-images.githubusercontent.com/64724041/110480047-0ea1af80-810c-11eb-8f44-327e3f475d24.jpeg)

**6)When rounded to tens place.**

![tens place1](https://user-images.githubusercontent.com/64724041/110480124-28db8d80-810c-11eb-9d32-cc1a3bc3a7c8.jpeg)

**Comment by DEEPALI-SUK** [comment]
**Sir, the previously written code for the integer, was giving wrong output for some of the inputs, so I have made some changes in that part also.**
**Like for the input 9999 when rounded to tens place it displayed the output 91000** 

![pic1](https://user-images.githubusercontent.com/64724041/110481183-49f0ae00-810d-11eb-8fdc-af080732fbf5.jpeg)

**and after I changed the code it showed the correct output.**

![pic2](https://user-images.githubusercontent.com/64724041/110481296-6bea3080-810d-11eb-9159-4dcbbdcd47ed.jpeg)

**Comment by DEEPALI-SUK** [comment]
Sir may I generate the PR now?

**Comment by DEEPALI-SUK** [comment]
Sir, may I make a PR?

**Comment by sairish2001** [comment]
No, will tell you tomorrow
There are some wrong outputs. Till then try to figure it out. With some online calculators or by solving yourself

**Comment by DEEPALI-SUK** [comment]
sir I have checked all these with online calculator, the outputs are matching

**Comment by sairish2001** [comment]
Can you please mention the calculator here?

> sir I have checked all these with online calculator, the outputs are matching

**Comment by DEEPALI-SUK** [comment]
https://www.calculator.net/rounding-calculator.html
for decimal part calculator's tenths = ones place in our calculator

**Comment by DEEPALI-SUK** [comment]
https://user-images.githubusercontent.com/64724041/110480047-0ea1af80-810c-11eb-8f44-327e3f475d24.jpeg
for this I am changing the code according to the online calculator

**Comment by sairish2001** [comment]
Appreciated!

**Comment by sairish2001** [comment]
![Untitled](https://user-images.githubusercontent.com/60106112/110508824-70bbde00-8127-11eb-9d2f-d6f6df3c1ef5.png)
I have a doubt in this output

**Comment by DEEPALI-SUK** [comment]
So according to our calculator ones place is the place just after the decimal point for floating numbers

**Comment by DEEPALI-SUK** [comment]
> ![Untitled](https://user-images.githubusercontent.com/60106112/110508824-70bbde00-8127-11eb-9d2f-d6f6df3c1ef5.png)
> I have a doubt in this output
> your 4th example

According to this calculator it is the tenths(1) place

**Comment by DEEPALI-SUK** [comment]
> https://user-images.githubusercontent.com/64724041/110480047-0ea1af80-810c-11eb-8f44-327e3f475d24.jpeg
> for this I am changing the code according to the online calculator

![WhatsApp Image 2021-03-09 at 22 33 27](https://user-images.githubusercontent.com/64724041/110509656-59312500-8128-11eb-85b6-b97b33cb8c63.jpeg)


I made the changes for this one also according to the online calculator

**Comment by sairish2001** [comment]
Are you using if the condition for particular inputs?

**Comment by DEEPALI-SUK** [comment]
Yes I have used if-else conditions to implement round off

**Comment by sairish2001** [comment]
make a PR, any further bugs will be treated in next isse
