### ISSUE TITLE
Create PNG Images of Shapes

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#24]
![equilateral](https://user-images.githubusercontent.com/60106112/110251633-670b6c80-7fa7-11eb-9782-446300fa96cd.png)

---

![isosceles](https://user-images.githubusercontent.com/60106112/110251638-6b378a00-7fa7-11eb-944b-d04a958e1145.png)

---

As the above images describe what's wrong in this.

Your task is to create PNG images for shapes:
- Equilateral Triangle [Click here](https://www.google.com/search?q=equilateral%20triangle%20calculator)
- Isosceles Triangle [Click Here](https://www.google.com/search?q=isosceles%20triangle%20calculator)
- Right-angle Triangle [Click Here](https://www.google.com/search?q=Right%20angle%20triangle%20calculator)
- Scalene Triangle [Click Here](https://www.google.com/search?q=Scalene%20Triangle%20calculator)
- Circle [Click Here](https://www.google.com/search?q=Circle%20Calculator)
- Trapezium [Click Here](https://www.google.com/search?q=Trapezium%20Calculator)
- Ellipse [Click Here](https://www.google.com/search?q=Ellipse%20Calculator)
- Parallelogram [Click Here](https://www.google.com/search?q=Parallelogram%20Calculator)
- Square
- Rectangle

Images for Square and Rectangle have already made but to keep the design same for all you have to create for it also.

---
Point to be Noted!

Be make sure to **Label** each diagram according to formulas.
You can refer to Google Search to see shapes and formulas, Use **Click Here** hyperlinks to visit Google Calculator

**Comment by sukhpreet-singh1** [comment]
can you assign me this issue under GSSOC 21

**Comment by sairish2001** [comment]
Feel free to ask your doubts,if any

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by janvi01** [comment]
I would like to work on this, can you assign it under GSSOC?

**Comment by sairish2001** [comment]
Deadline 13 March,2021(11:59 PM IST)

**Comment by Muskan-creator** [comment]
I would like to work on this issue.Please assign it to me.I will create png files for all shapes.
