### ISSUE TITLE
Check Empty field

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#26]
In DIVIDE Calculator
![PicsArt_03-08-11.29.04.jpg](https://user-images.githubusercontent.com/60106112/110281802-61dc0b00-8003-11eb-89ed-bafb43cf12cb.jpg)

---

In Multiplication Table Calculator
![PicsArt_03-08-11.32.50.jpg](https://user-images.githubusercontent.com/60106112/110281859-7b7d5280-8003-11eb-8e7e-d0c00764e039.jpg)

---

In Ascending and Descending Order Calculator

![PicsArt_03-08-11.35.25.jpg](https://user-images.githubusercontent.com/60106112/110281888-8a640500-8003-11eb-85fd-14681ec08fee.jpg)

---

Roman/Arabic Numerals Calculator

![PicsArt_03-08-11.41.30.jpg](https://user-images.githubusercontent.com/60106112/110281933-9c45a800-8003-11eb-9e9e-246fce912b59.jpg)

---
Your Task is to check if these fields are empty, then it should not show these kind of outputs.

Logic for all these Calculators is in [logicjavascript.js](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/appjs/logicjavascript.js)

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue under GSSOC 21

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by Faizanrz7** [comment]
@sairish2001 I would like to work in this issue as a part of gssoc'21, assign me if possible.

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by sairish2001** [comment]
@sukhpreet-singh1 Any Update?

**Comment by sukhpreet-singh1** [comment]
yes i am working on it

**Comment by Faizanrz7** [comment]
@sairish2001  I have solved the issue, can I create PR ??

**Comment by sairish2001** [comment]
No, someone else is working on it

**Comment by sairish2001** [comment]
@sukhpreet-singh1 any update? can you solve this issue?

**Comment by Faizanrz7** [comment]
@sairish2001  Ok

**Comment by sairish2001** [comment]
Deadline 13 March,2021(11:59 PM IST)

**Comment by sukhpreet-singh1** [comment]
solved for multiplication and divide ,sorry for taking time i was going through whole code as i will work with this project for GSSOC
