### ISSUE TITLE
Create Trigonometry values Table

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#28]
Using HTML table create a Trigonometry table to display all these values.

![maxresdefault](https://user-images.githubusercontent.com/60106112/110297480-88a53c00-8019-11eb-8cc7-a100a99705e6.jpg)

---

Since we are using [Bootstrap](https://getbootstrap.com/docs/4.0/getting-started/introduction/) framework for styling.

You can use `class="table table-bordered"`
```
<table class="table table-bordered">
    ......
</table>
```
For documentation of Bootstrap Tables [Click here](https://getbootstrap.com/docs/4.1/content/tables/)

---

Use LaTeX text to display values
`\[\frac{3}{4}\]` ![3/4](https://latex.codecogs.com/gif.latex?\frac{3}{4})

`\[\sqrt{36}\]` ![3/4](https://latex.codecogs.com/gif.latex?\sqrt{36})

---

You need to Create a Option in sidenav:
![Untitled](https://user-images.githubusercontent.com/60106112/110299957-52b58700-801c-11eb-98c4-5279588be35b.png)
and create a `<div id='trigonovaluestable'>` then add this **Id** into [function openit()](https://github.com/sairish2001/makesmatheasy.github.io/blob/0c589bd921253ffcb57e30471a45c0767a4d0840/appjs/index.js#L13) array then add sidenav bar's button link to [this file](https://github.com/sairish2001/makesmatheasy.github.io/blob/0c589bd921253ffcb57e30471a45c0767a4d0840/appjs/working.js#L21)

**Comment by haripriya9647** [comment]
hey I would like to work on this issue

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any.

**Comment by haripriya9647** [comment]
Where does project discussions takes place??

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by janvi01** [comment]
I would like to work on this issue under GSSOC '21.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by srimontidutta** [comment]
Can I contribute to this issue as a part of GSSoC 21?

**Comment by janvi01** [comment]
where do we have to add our div trigonovaluestable?
I have added in div container but it isn't going well.

**Comment by sairish2001** [comment]
Sorry! issue is already assigned

**Comment by sairish2001** [comment]
@janvi01 I have added a <div id='trigonovaluestable'> in index.html. Move further with it
