### ISSUE TITLE
Work on binary calculations 

### ISSUE THREAD

**Issue by coding-geek21** [sairish2001/makesmatheasy.github.io#282]
Can you please assign this task to me i would like to work on binary calculations part, !'m a GSSoC'21 participant

**Comment by sairish2001** [comment]
Can you please elaborate, what type of binary Calculations you are talking about?

**Comment by coding-geek21** [comment]
In the menu i found binary calculations tab ,I would like to develop binary to decimal converter

**Comment by shrey27tri01** [comment]
@coding-geek21 We already a binary to decimal converter. Hence, I'm closing this issue as of now. However, feel free to work on other issues!
