### ISSUE TITLE
Documentation for Makes Math Easy

### ISSUE THREAD

**Issue by robin025** [sairish2001/makesmatheasy.github.io#31]
This feature will provide easy-to-read documentation to the users.

Hey @sairish2001, I have used this project and I think I am facing some issues while doing some calculations, not because of the code but because of less documentation available on this project 

So here my suggestion request!
So while going through the project I was not able to fill the blanks correctly in the [website](https://sairish2001.github.io/makesmatheasy.github.io/) 
we can use the Jekyll theme which is a static website generator that’s designed for building minimal, static blogs and pages to be hosted on GitHub Pages which we can use to create some awesome documentation for this project so that every user can learn how to use this tool.
With the help of Jekyll, it strips everything down to the bare minimum, eliminating a lot of complexity
1.We can easily transform our plain text into static website pages and blogs.
2.It requires no databases, cms or any updates
3.It supports static HTML, CSS javascript, and even Markdown, so with the help of markdown we can easily use all types of labels and other stuff
4.What’s best is it goes well with Github-Pages
5.It loads faster

At last, creating some good documentation for this project will help many users to use this tool easily.

**I would like to work on this issue**

looking forward to your reply
thanks

**Comment by sairish2001** [comment]
Go ahead, Good Issue.

**Comment by srimontidutta** [comment]
Can I contribute to this project's documentation as a part of GSSoC 21?

**Comment by sairish2001** [comment]
@srimontidutta  Sorry! issue is already assigned

**Comment by sairish2001** [comment]
[Makes Math Easy Documentation](https://github.com/sairish2001/Makes-Math-Easy-Documentation/) Repository

Go ahead with this Repository and make your valuable Contribution @robin025

**Comment by robin025** [comment]
thankyou @sairish2001

**Comment by sairish2001** [comment]
Deadline 14 March,2021(11:59 PM IST)

**Comment by sairish2001** [comment]
Will you be able to complete it by today?

**Comment by robin025** [comment]
> Will you be able to complete it by today?

Yes

**Comment by sairish2001** [comment]
Deadline extended 15 March,2021 (11:59 PM IST)

**Comment by sairish2001** [comment]
Make a PR in [Documentation Repository](https://github.com/sairish2001/Makes-Math-Easy-Documentation)
