### ISSUE TITLE
Adding general solutions of some trigonometric equations

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy.github.io#331]
I would like to add general solutions of trigonometric equation like sintheta= 0 then theta=npi and many more such equations.
Please assign this issue to me

**Comment by RaveenaBhasin** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by RaveenaBhasin** [comment]
@sairish2001 I have created the PR. Please review it .
