### ISSUE TITLE
properties of triangles

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy.github.io#340]
I would like to add properties of triangles like circumcenter,circumradius,incentre, orthocentre and their properties
There are lots of identities for solution of triangles

**Comment by khareyash05** [comment]
Hey @sairish2001 Could you pls help me with a thing

**Comment by sairish2001** [comment]
Go ahead
Feel free to ask your doubts,if any
Deadline 27 March,2021 (11:59 PM IST)

**Comment by khareyash05** [comment]
I am not just getting how to add formulae as it is getting distorted Could you pls tell me how to do that

**Comment by khareyash05** [comment]
[1)\space\int x^n \,dx\space=\frac{x^{(n+1)}}{n+1}+c\] like this 
Where can I find the documentation @sairish2001

**Comment by khareyash05** [comment]
![2021-03-22 (1)](https://user-images.githubusercontent.com/60147732/111983400-1ad83480-8b30-11eb-88e5-9b8b4181cda7.png)
See  how am i typing the formula
![2021-03-22 (2)](https://user-images.githubusercontent.com/60147732/111983484-2f1c3180-8b30-11eb-8913-55e41d8b4f24.png)
This is how I want it  way better than mine 
Did u understood what i meant to say ? @sairish2001

**Comment by sairish2001** [comment]
This is LaTeX text
https://www.overleaf.com/learn/latex/Mathematical_expressions

Check this out

**Comment by khareyash05** [comment]
@sairish2001 Created a PR Have a look!
