### ISSUE TITLE
Updating integration and definite integration formulae section

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy.github.io#358]
I would like to add 2-3 important formulae in integration formulae sections and would like to add conditions according to which properties in definite integration is applied.
Please assign this issue to me.

**Comment by shrey27tri01** [comment]
@RaveenaBhasin Can you please elaborate what formulae you're suggesting to add?
Other than that, please go ahead with the issue :)
Deadline 27th March 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I would like to that indefinite integration formula of exponential function.
Eg: Integration of e^axsinbx

**Comment by shrey27tri01** [comment]
@RaveenaBhasin Sure, you can go ahead with this :)
