### ISSUE TITLE
on changing to light mode some text getting displayed

### ISSUE THREAD

**Issue by madihamallick** [sairish2001/makesmatheasy.github.io#360]
## **Describe the bug**

on changing the mode to light some text is getting displayed on the screen that need to be removed

## **Possible solution**

I would like remove that.

## **Screenshots**
![Capture](https://user-images.githubusercontent.com/70858557/112107015-6fcd8680-8bd4-11eb-8f21-ae45488a32ed.PNG)

I would like to work on this issue, Please assign this to me under GSSoC.

**Comment by shrey27tri01** [comment]
This issue has occurred most probably due to a merge conflict on a PR. 
You can go ahead with this :)
Deadline 27th March 11:59 PM IST

**Comment by madihamallick** [comment]
Okay. Thank you.
