### ISSUE TITLE
Wrong answer of sum of A.P. when last term is given

### ISSUE THREAD

**Issue by RaveenaBhasin** [sairish2001/makesmatheasy.github.io#361]
When we are calculating the sum of AP by knowing the last term result is coming wrong.
I would like to correct this issue. Please assign this to me.
<img width="949" alt="2021-03-23 (2)" src="https://user-images.githubusercontent.com/73697080/112108569-634a2d80-8bd6-11eb-9755-3d10f3f30bb8.png">

**Comment by shrey27tri01** [comment]
@RaveenaBhasin You can go ahead with this :)
Deadline 27th March 11:59 PM IST

**Comment by RaveenaBhasin** [comment]
I have made the PR kindly review it
