### ISSUE TITLE
Bug in sum of GP calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#366]
## **Describe the bug**
If a common ratio less than 1 is entered  then the sum of GP calculator always shows the sum as 0
![Screenshot (122)](https://user-images.githubusercontent.com/66053534/112118659-9bf00400-8be2-11eb-833c-b3084862392c.png)

Please assign this to me.
#GSSoC21

**Comment by AB-san** [comment]
Please kindly me assign me this issue!! I will start working on it as soon as possible

**Comment by kanishka8276** [comment]
Hey @AB-san I opened this issue so that I can work on it . I am also a GsSOC'21 participant.

**Comment by AB-san** [comment]
> Hey @AB-san I opened this issue so that I can work on it . I am also a GsSOC'21 participant. You don't have to solve a issue until it is assigned to you.

But you need to ask them to assign you right? You didnt at that time when i saw the issue so thats y i worked on it

**Comment by AB-san** [comment]
> Hey @AB-san I opened this issue so that I can work on it . I am also a GsSOC'21 participant. You don't have to solve a issue until it is assigned to you.

I am really sorry i didnt knew that we cant work on the issue until its assigned to me

**Comment by AB-san** [comment]
And dont mind but the pull request i made solves another issue which is not mentioned in the one that you have created i.e, when r==1

**Comment by kanishka8276** [comment]
Yes, I would suggest create another issue for r==1 and get it assigned so that your PR is merged!

**Comment by sairish2001** [comment]
Go ahead! @AB-san
Deadline 28 March,2021 (11:59 PM IST)
