### ISSUE TITLE
Maximum limit for the numbers while generating Multiplication table.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [sairish2001/makesmatheasy.github.io#37]
- While generating the multiplication table if the numbers are very large then the browser hangs. So we need to provide an upper limit for the numbers.
- Also should add a scrollbar so we are able to scroll quickly through the table.

**Comment by srisatya1197** [comment]
I want to contribute to maximum Limit for the numbers while generating multiplication table issue. Please assign me this task as a part of GSSoC'21

**Comment by Karthik-Nayak98** [comment]
Shall I add an alert message to show that the numbers are crossing the limit?

**Comment by sairish2001** [comment]
Fine, it should trigger oninput.
