### ISSUE TITLE
Bug in EMI calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#376]
## **Describe the bug**

in EMI calculator if rate is entered in decimal value it is showing wrong result.

![Screenshot (132)](https://user-images.githubusercontent.com/66053534/112143084-6ad0fd00-8bfd-11eb-9ec3-e561bb9534f0.png)
![Screenshot (133)](https://user-images.githubusercontent.com/66053534/112143090-6c9ac080-8bfd-11eb-91f6-d9a1fb08e2ee.png)

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 29 March,2021 (11:59 PM IST)
