### ISSUE TITLE
Bug in interest calculator.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#378]
## **Describe the bug**
It's rounding up the simple interest to ones .
Like if simple interest is 30.4 it is showing 30 only.
![Screenshot (134)](https://user-images.githubusercontent.com/66053534/112149342-e08c9700-8c04-11eb-93fd-58c1b22f5496.png)
![Screenshot (135)](https://user-images.githubusercontent.com/66053534/112149348-e2eef100-8c04-11eb-8d80-ff5e5b20c24d.png)

Please assign this to me.

**Comment by sairish2001** [comment]
Go ahead!
Deadline 27 March,2021 (11:59 PM IST)
