### ISSUE TITLE
dropDown menu image bug

### ISSUE THREAD

**Issue by Pranjal-Jayaswal** [sairish2001/makesmatheasy.github.io#38]
The adjacent image in the DropDown menuList  (inside sideBar) shall show the correct collapsing direction.
![Screenshot (16)_LI](https://user-images.githubusercontent.com/63522945/110429620-39224700-80d1-11eb-970b-b862a0e03c03.jpg)

**Comment by Pranjal-Jayaswal** [comment]
I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by sairish2001** [comment]
Go ahead, Feel free to ask your doubts, if any
