### ISSUE TITLE
add animation on search bar and background 

### ISSUE THREAD

**Issue by mridulabatra** [sairish2001/makesmatheasy.github.io#44]
the search bar is the first thing that appears it looks a little dull right now, adding some animation and design will make it look better

**Comment by mridulabatra** [comment]
hello sir, I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by mridulabatra** [comment]
okay, thank you sir

**Comment by sairish2001** [comment]
@aanchalrakheja Sorry! already assigned. Check out some other issues, or create a new one

**Comment by sairish2001** [comment]
Try to remove the white line below field
```
.form__field {
    _____
}
```

it's occurring due to form__field class

**Comment by sairish2001** [comment]
Instead of using red color, use pink color
`background-color:var(--apppink);`

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21 . Can you please assign this to me under GSSOC'21?

**Comment by sairish2001** [comment]
Deadline crossed, but I think you have completed your work, due to some conflicts PR not merged

So Deadline extended 13 March,2021 (11:59 PM IST)

Do make PR with the updated code to avoid conflicts

**Comment by mridulabatra** [comment]
Sir i have made some changes that will take the content under the search bar and the calculator that was going to extreme left i corrected that too then i tried sending the pull request again and i was not able to do so

**Comment by mridulabatra** [comment]
Sir also can u tell me what other changes i should make to avoid the conflicts in PR thank you

**Comment by sairish2001** [comment]
Just keep your code updated
Then probably no conflicts occur.

Today some PR's got merged, so kindly update your code.

**Comment by mridulabatra** [comment]
Okh sir

**Comment by sairish2001** [comment]
Deadline is near

**Comment by mridulabatra** [comment]
sir i have tried several times now its giving error saying "please make sure you have the correct access rights and repository exists".

**Comment by sairish2001** [comment]
Have you done with your work?

**Comment by mridulabatra** [comment]
Yes sir

**Comment by sairish2001** [comment]
Try to make PR without CLI, may be it works

**Comment by mridulabatra** [comment]
Okh sir

**Comment by mridulabatra** [comment]
Sir still not working and now its showing nothing to commit working tree clean

**Comment by sairish2001** [comment]
Ping a message in our discord channel

**Comment by janvi01** [comment]
I would like to work on this.

**Comment by bishalshaw-164** [comment]
Hi
I would like add animation on search bar and background,
Would you please assign me to do this.
