### ISSUE TITLE
Complete logic/working of Calculator for Shapes

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#46]
Working for
- Square
- Rectangle

is already done, you can check it out [visit](https://sairish2001.github.io/makesmatheasy.github.io/)

But for the rest of the Calculators (red color in the image) apply similar working, and fields according to formulas:
You can refer to Google Calculator for these, which makes you more comfortable
- Isosceles Triangle [Click Here](https://www.google.com/search?q=isosceles%20triangle%20calculator)
- Right-angle Triangle [Click Here](https://www.google.com/search?q=Right%20angle%20triangle%20calculator)
- Scalene Triangle [Click Here](https://www.google.com/search?q=Scalene%20Triangle%20calculator)
- Circle [Click Here](https://www.google.com/search?q=Circle%20Calculator)
- Trapezium [Click Here](https://www.google.com/search?q=Trapezium%20Calculator)
- Ellipse [Click Here](https://www.google.com/search?q=Ellipse%20Calculator)
- Parallelogram [Click Here](https://www.google.com/search?q=Parallelogram%20Calculator)

![Untitled](https://user-images.githubusercontent.com/60106112/110471153-cbdada00-8101-11eb-9405-49ced7b52ce8.png)

**Comment by aanchalrakheja** [comment]
Would like to contribute to this issue. Would need some guidance though. Please assign it to me.

**Comment by aanchalrakheja** [comment]
Thank u so much. Sure :)

**Comment by aanchalrakheja** [comment]
Hey! Can u guide me about the calculation part. I have successfully added the input fields.

**Comment by aanchalrakheja** [comment]
@janvi01 yes i'm. Would u like to work together if we can?

**Comment by sairish2001** [comment]
Sorry @janvi01 , we can't allow multiple participants to work on single issue, under GSSOC'21

**Comment by aanchalrakheja** [comment]
I have a doubt

**Comment by sairish2001** [comment]
Yes!

**Comment by Muskan-creator** [comment]
I would like to contribute this issue.Please assign it to me.
