### ISSUE TITLE
Use LaTeX text in displaying Trigonometry values

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#48]
![Untitled](https://user-images.githubusercontent.com/60106112/110472758-c4b4cb80-8103-11eb-933a-e9aba7362502.png)

Just replace these Text with LaTeX (Math Text)
Not familiar with LaTeX?
Not a difficult or complex task

---

for displaying
- ![3/4](https://latex.codecogs.com/gif.latex?\frac{3}{4}) use `\[\frac{3}{4}\]`
- ![sqrt(3)](https://latex.codecogs.com/gif.latex?\sqrt{3}) use `\[\sqrt{3}\]`
- ![\frac{\sqrt{3}}{2}](https://latex.codecogs.com/gif.latex?\frac{\sqrt{3}}{2}) use `\[\frac{\sqrt{3}}{2}\]`
- ![\sin\theta](https://latex.codecogs.com/gif.latex?\sin\theta) use `\[\sin\theta\]`
- ![60^{\circ}](https://latex.codecogs.com/gif.latex?60^{\circ}) use `\[60^{\circ}\]`

just you need to make changes in [index.html](https://github.com/sairish2001/makesmatheasy.github.io/blob/9e0d86887b1657aa6b96ba5884c9ded2afe30349/index.html#L951) line 951 onwards

Example:
Original code
```
<tr>
    <th scope="row">sin θ</th>
    <td>0</td>
    <td>1/2</td>
    <td>1/√2</td>
    <td>√3/2</td>
    <td>1</td>
</tr>
```

with LaTeX Text code
```
<tr>
    <th scope="row">\[\sin\theta\]</th>
    <td>\[0\]</td>
    <td>\[\frac{1}{2}\]</td>
    <td>\[\frac{1}{\sqrt{2}}\]</td>
    <td>\[\frac{\sqrt{3}}{2}\]</td>
    <td>\[1\]</td>
</tr>
```

**Comment by paulamib123** [comment]
Hi!
I am a GSSOC'21 Participant.
I would like to contribute to this issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by paulamib123** [comment]
Thanks for assigning this to me.
I had a question
For the values that are undefined should I make any changes? or just leave it as it was before?

**Comment by sairish2001** [comment]
Use LaTeX 
`\[Not \space Defined\]`

**Comment by paulamib123** [comment]
Thank You!

**Comment by abhinav5481** [comment]
Hi,
I would like to work on this issue for GSsoc'21 . Could you please assign it to me?

**Comment by sairish2001** [comment]
@paulamib123 Your [recent PR](https://github.com/sairish2001/makesmatheasy.github.io/pull/52) is creating issue while loading the whole index.html page

**Comment by paulamib123** [comment]
Okay. I found the issue i'll fix it right now.

**Comment by aanchalrakheja** [comment]
hey! can i contribute to this issue.
