### ISSUE TITLE
Create Angle plotter

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#5]
**Input Angle: 120°**
**Output:**
![PicsArt_03-02-02.31.58.jpg](https://user-images.githubusercontent.com/60106112/109624331-18537200-7b64-11eb-9510-b65c438ed494.jpg)
(image is just for illustration)

----
You can use any library if wants, or if wants to design your own logic then most welcome.**(Only libraries which compute in client side are allowed)**
Feel free to contribute in any way

**Comment by sairish2001** [comment]
Hint!
Can be implemented using HTML CANVAS

by drawing lines two lines with a particular angle in between them.

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by Swetha126** [comment]
I am a part of GSSOC'21 
I am interested in working on this issue

**Comment by zhcet19** [comment]
Can you assign me this task,I am participant of GSSOC' 21

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any

**Comment by sairish2001** [comment]
Deadline 14 March,2021(11:59 PM IST)

**Comment by zhcet19** [comment]
@sairish2001 please assign me this issue

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 20 March,2021 (11:59 PM IST)

**Comment by zhcet19** [comment]
![Uploading gssoc10.png…]()

**Comment by zhcet19** [comment]
![gssoc10](https://user-images.githubusercontent.com/55043876/111858740-448f3100-8961-11eb-8a3b-7e69b14f2103.png)

**Comment by zhcet19** [comment]
@sairish2001 this is what i have currently made ,is this sufficient

**Comment by sairish2001** [comment]
Can you please show some more test cases:
120°
59°
75°

**Comment by zhcet19** [comment]
Sure @sairish2001

**Comment by zhcet19** [comment]
![gssoc11](https://user-images.githubusercontent.com/55043876/111861328-47931d00-8973-11eb-8115-bffc36e69749.png)

**Comment by zhcet19** [comment]
![gssoc12](https://user-images.githubusercontent.com/55043876/111861337-6abdcc80-8973-11eb-904c-3c22f491c034.png)

**Comment by sairish2001** [comment]
Can you display numbers, in the y and x axis? which indicates the angle number

**Comment by zhcet19** [comment]
Yes I will do it

**Comment by zhcet19** [comment]
![gssoc1](https://user-images.githubusercontent.com/55043876/111877212-3f190180-89c8-11eb-835b-4e3c4d812d0f.png)

**Comment by zhcet19** [comment]
@sairish2001 is it now fine

**Comment by sairish2001** [comment]
Great, go ahead with PR
