### ISSUE TITLE
Create helpjavascript.html page

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#6]
Since this project's working is entirely based upon JavaScript, but sometimes when JavaScript is disabled in the user's browser, the app will not work. So create a [HTML page](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/helpjavascript.html) to guide user on how to enable JavaScript in your browser.
For different Browsers:
- Google Chrome
- Internet Explorer
- Microsoft Edge
- Mozilla Firefox
- Opera
- Safari

Note!
Don't use any JavaScript on this page.

**Comment by SHAIMA-HAQUE** [comment]
I would love to work on this issue. Could you please assign this to me. I am new to open source so I would take some time to implement it. You would like this to be added to the helpjavascript.html file right?

**Comment by sairish2001** [comment]
yeah! you are right! update the [helpjavascript.html](https://sairish2001.github.io/makesmatheasy.github.io/helpjavascript.html) page

**Comment by sairish2001** [comment]
Thanks for showing interest in this Project.
Take your time, to understand the codebase and feel free to ask doubts, if any. I will help you with that.

I will ask you the update in next 3 days.

**Comment by SHAIMA-HAQUE** [comment]
Ok Thank you!

**Comment by SHAIMA-HAQUE** [comment]
I have created a PR ,please review and tell me if there are any changes.
