### ISSUE TITLE
Responsive Calculator

### ISSUE THREAD

**Issue by gnikita432** [sairish2001/makesmatheasy.github.io#62]
In mobile-view, the calculator is taking the whole width of the screen and that's why the last number is difficult to see.
![mi](https://user-images.githubusercontent.com/61223163/110570442-e6ea3000-817b-11eb-9ec0-3a8e075193df.PNG)
Some margin or padding can be added to the calculator.
I am a GSSOC'21 participant. kindly assign me this issue under gssoc'21.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by sairish2001** [comment]
Deadline is 15 March,2021 (11:59 PM)

**Comment by gnikita432** [comment]
sure, thank you for assigning.

**Comment by niya210** [comment]
@sairish2001 sir, could you please assign any task to me?

**Comment by sairish2001** [comment]
Deadline 14 March,2021(11:59 PM IST)

**Comment by gnikita432** [comment]
hey @sairish2001 the issue is already solved and the branch is also merged.

**Comment by sairish2001** [comment]
Yeah! but I reported some bug in it
