### ISSUE TITLE
the homepage should contain some introduction about the website, maybe a tagline or so and it can be made more appealing

### ISSUE THREAD

**Issue by aanchalrakheja** [sairish2001/makesmatheasy.github.io#63]
I would love to work on this issue and make the homepage more attractive, adding logo, a tagline or so.

**Comment by Swetha126** [comment]
Hey! I am a GSSOC'21 participant 
I would like to make the homepage attractive by adding precise and catchy content for the introduction and an appropriate tagline.
Can you please assign me this issue?

**Comment by sairish2001** [comment]
[#13](https://github.com/sairish2001/makesmatheasy.github.io/issues/13)
Same issue is already open, and one of our participant is working on it.
