### ISSUE TITLE
The 'Home' button from sidebar is inactive and not directing to homepage when clicked 

### ISSUE THREAD

**Issue by akshay399** [sairish2001/makesmatheasy.github.io#64]
i am a GGSOC member and can i please work on this issue?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

**Comment by akshay399** [comment]
please review the pull request, thanks

**Comment by sairish2001** [comment]
Have you checked it?
is it working fine!

after clicking home button it should close all the Calculators,

see appjs/working.js for the proper working of SideNav

**Comment by ayu222220** [comment]
Would like it work on it. Can you assign me?
From GSSOC'21.

**Comment by jyotsana3108** [comment]
I would like to work on this issue. I am a participant of GSSOC 21. Please assign this issue to me.

**Comment by gritika18** [comment]
Hii! I'm a GSSOC participant and i would lie to work on this issue. Could you please assign this to me?
