### ISSUE TITLE
Make Website Screen Size Friendly

### ISSUE THREAD

**Issue by Aanchal116** [sairish2001/makesmatheasy.github.io#66]
I'm a GSSOC'21 participant. I would like to work on this issue to make the website mobile and tablet friendly. Please assign me this issue.

**Comment by vmk8826** [comment]
I have been working on this issue since last week can you assign it to me I am a GSoC 2021 participant.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

Deadline 16 March,2021 (11:59 PM IST)

**Comment by Aanchal116** [comment]
> Feel free to ask your doubts, if any
> 
> Deadline 16 March,2021 (11:59 PM IST)

Sure, Thankyou so much.
