### ISSUE TITLE
issue and pull request templates

### ISSUE THREAD

**Issue by Sloth-Panda** [sairish2001/makesmatheasy.github.io#68]
as there are no issue and pull request templates in this repo so would like to add those

**Comment by Sloth-Panda** [comment]
@sairish2001 can I work on this?

**Comment by sairish2001** [comment]
Can you please elaborate, what does this issue mean

**Comment by Sloth-Panda** [comment]
@sairish2001 basically an issue template will state what sort of issue it is with its complete description and will represent an issue in a systematic manner while a pr template basically means the same and in addition builds can be configured over it so that if some build fail you can ask for changes in the pr

**Comment by sairish2001** [comment]
how would you implement this as a markdown file?

**Comment by Sloth-Panda** [comment]
yes @sairish2001

**Comment by sairish2001** [comment]
Go Ahead
