### ISSUE TITLE
Create Unit Converter Calculator

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#7]
Create a Unit Converter Calculator to convert Units

**Length**

- Millimeter
- Centimeter
- Meter
- Kilometer
- Inch
- Foot
- Yard
- Mile
- Nautical mile
- Mil

**Area**

- Acre
- Are
- Hectare
- Square centimeter
- Square foot
- Square inch
- Square meter

**Volume**

- Gallon (US)
- Gallon (UK)
- Liter
- Milliliter
- Cubic centimeter (cc)
- Cubic meter
- Cubic inch
- Cubic foot

**Mass**

- Ton
- Ton (UK)
- Ton (US)
- Pound
- Ounce
- Kilogram
- Gram

**Temperature**

- Celsius
- Fahrenheit
- Kelvin

**Comment by satyampgt4** [comment]
I would like to work on this issue as a part of GSSOC 2021 @sairish2001 please assign it to me

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any
