### ISSUE TITLE
Modify Clear C in calculator

### ISSUE THREAD

**Issue by janvi01** [sairish2001/makesmatheasy.github.io#71]
<img width="734" alt="Screenshot 2021-03-10 at 5 28 52 PM" src="https://user-images.githubusercontent.com/34344234/110626019-381f1180-81c6-11eb-9642-20181e905002.png">

On clicking C clear, the result doesn't get cleared.

<img width="734" alt="Screenshot 2021-03-10 at 5 29 14 PM" src="https://user-images.githubusercontent.com/34344234/110626112-538a1c80-81c6-11eb-8b23-bc059b8ba9c5.png">

I would like to solve this issue.

**Comment by sairish2001** [comment]
Actually it's not a issue.
Keeping answer in ans field causes no harm, Sometimes user wants to see previous answer so that's why it's not a issue.
