### ISSUE TITLE
Responsive Font Size

### ISSUE THREAD

**Issue by sairish2001** [sairish2001/makesmatheasy.github.io#8]
Make Font-Size responsive for whole application

Here's an example
![PicsArt_03-04-06 30 01](https://user-images.githubusercontent.com/60106112/109967663-b3407d80-7d17-11eb-971b-a40de2736921.jpg)

Make a good looking Symmetry in Font-Sizes

**Comment by vmk8826** [comment]
can you assign this issue to me please

**Comment by vmk8826** [comment]
I am a GSoC 2021 aspirant

**Comment by sairish2001** [comment]
Feel Free to ask your doubts, if any

**Comment by sairish2001** [comment]
[Read](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/CONTRIBUTING.md)

**Comment by Ruchip16** [comment]
@sairish2001 Can I work on this issue?

**Comment by sairish2001** [comment]
@Ruchip16 This issue is already assigned. Sorry! 
Explore other issues

**Comment by vmk8826** [comment]
can you give me the reference to the file in which the CSS of this page is present?

**Comment by vmk8826** [comment]
is it overflowing in mobile devices, because I did not experience any overflow in my laptop?

**Comment by sairish2001** [comment]
[css/style.css](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/css/style.css)
also maybe inline CSS also used in (index.html)

**Comment by vmk8826** [comment]
okay
i found the id "inputlaplace" but I am not able to  find its reference

**Comment by sairish2001** [comment]
> is it overflowing in mobile devices, because I did not experience any overflow in my laptop?

Yes, Overflow occurs in mobile devices

**Comment by sairish2001** [comment]
> okay
> i found the id "inputlaplace" but I am not able to find its reference

You are talking about in CSS reference?
look into 
```
.katex{

}
```
in [css/style.css](https://github.com/sairish2001/makesmatheasy.github.io/blob/main/css/style.css)

**Comment by vmk8826** [comment]
![IMG-20210308-WA0029.jpeg](https://user-images.githubusercontent.com/68069180/110349633-e2792680-8058-11eb-819d-f9a7a2d563fa.jpeg)

**Comment by vmk8826** [comment]
![IMG_20210308_215433.jpg](https://user-images.githubusercontent.com/68069180/110349687-f2910600-8058-11eb-82e0-f17cf419281e.jpg)

**Comment by vmk8826** [comment]
is this good enough

**Comment by sairish2001** [comment]
Fine! but don't change the placeholder text's alignment,make it left align.

**Comment by vmk8826** [comment]
okay

**Comment by sairish2001** [comment]
Try to make font-size in between 20px to 25px; whichever looks good.

**Comment by vmk8826** [comment]
![IMG_20210308_220104.jpg](https://user-images.githubusercontent.com/68069180/110350511-cfb32180-8059-11eb-8301-d17ac53a2990.jpg)

**Comment by vmk8826** [comment]
now

**Comment by sairish2001** [comment]
great!

**Comment by sairish2001** [comment]
Do you know. How to enable mobile view in chrome desktop?

**Comment by vmk8826** [comment]
I am not able to get that overflow bug as I am using a PC how do I see that

**Comment by sairish2001** [comment]
Steps to view Mobile view in Chrome desktop
- Ctrl+Shift+I (to open Inspect)
![Untitled](https://user-images.githubusercontent.com/60106112/110351077-6ed81900-805a-11eb-8671-79109d656cb6.png)

**Comment by vmk8826** [comment]
okay got it

**Comment by sairish2001** [comment]
Instead of clicking picture from Mobile phone of PC you can use
- Print Screen button
- then Ctrl+V to paste picture

**Comment by vmk8826** [comment]
![image](https://user-images.githubusercontent.com/68069180/110358619-a1860f80-8062-11eb-8d97-f184e65a3111.png)

**Comment by vmk8826** [comment]
do you like it?

**Comment by vmk8826** [comment]
or this

**Comment by vmk8826** [comment]
![image](https://user-images.githubusercontent.com/68069180/110359025-004b8900-8063-11eb-8212-4cd4e3a49eb1.png)

**Comment by sairish2001** [comment]
> ![image](https://user-images.githubusercontent.com/68069180/110358619-a1860f80-8062-11eb-8d97-f184e65a3111.png)
> 

This looks good

**Comment by vmk8826** [comment]
should i generate a pull request

**Comment by vmk8826** [comment]
it is responsive now

**Comment by sairish2001** [comment]
Go ahead with Pull Request

**Comment by vmk8826** [comment]
done

**Comment by sairish2001** [comment]
Will review by Tomorrow

**Comment by vmk8826** [comment]
okay can you give me something else to work on

**Comment by vmk8826** [comment]
did you check it

**Comment by sairish2001** [comment]
Actually your PR is creating Conflicts.
I saw your changes, you made changes in css/style.css
am I Right?
```
.katex{
    font-size: 25px !important;
    display: flex;
}
```
You need to only make PR for style.css file, but you included index.html and simplecal.js  also which creating conflicts while merging your PR

**Comment by vmk8826** [comment]
okay

**Comment by vmk8826** [comment]
will do in some time thanks

**Comment by vmk8826** [comment]
well I resolved the pull request can you check it again

**Comment by vmk8826** [comment]
can you please help me with what should I do as I am not able to resolve the conflict

**Comment by sairish2001** [comment]
just make a New PR by uploading only style.css file

**Comment by vmk8826** [comment]
I am not uploading any other file the code is getting changed by itself I tried to fork the repo again but the same error persists all the time

**Comment by vmk8826** [comment]
Can you check the PR I have uploaded just one file, i.e style.css

**Comment by vmk8826** [comment]
did you check it?

**Comment by sairish2001** [comment]
Kindly update the whole code in your local machine, to resolve the conflicts

**Comment by vmk8826** [comment]
okay got the problem thank you

**Comment by vmk8826** [comment]
a need a little help please

**Comment by sairish2001** [comment]
Just refork the repository
and open the style.css file directly on GitHub on your browser
click on edit button
make your edits
just commit changes

Then you will see a Compare Pull Request Option there make a new PR

**Comment by vmk8826** [comment]
okay thanks

**Comment by sairish2001** [comment]
Please make a valid PR before 12 March,2021 (11:59 PM IST) without conflicts

It's a deadline

**Comment by vmk8826** [comment]
done
there are no conflicts now
