### ISSUE TITLE
Add arrows on  the scroll bar on the right of the calculator list .

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#84]
There are no arrows on the scroll bar in the right of the calculator list. Arrows will be better and make it more user friendly.
Please assign this to me.
#GsSOC'21

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 13 March,2021(11:59 PM IST)

**Comment by kanishka8276** [comment]
Ok! Thank you ☺️
