### ISSUE TITLE
Adding unit conversion of speed and time also in the unit converter.

### ISSUE THREAD

**Issue by kanishka8276** [sairish2001/makesmatheasy.github.io#85]
We can add options for unit conversion of speed and time in the unit converter.
Please assign this to me.
#GsSOC'21

**Comment by sairish2001** [comment]
I already assigned you 1 Major and 1 Minor issue, would you manage to deliver the outcome upto 16 March,2021 ? as it's also a Major issue.

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 17 March,2021(11:59 PM IST)

**Comment by Krishan-2000** [comment]
Can I work on this issue? 
Please assign this issue to me @sairish2001 
#GsSOC'21
