### ISSUE TITLE
Revamping Question area 

### ISSUE THREAD

**Issue by shairanshrawat** [sairish2001/makesmatheasy.github.io#89]
The current question areas are very dull. I want to make it attractive by changing its position and adding the like and dislike button along with the share and bookmark buttons.
 
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021?
Thank you

**Comment by sairish2001** [comment]
Which question area are you talking about?

**Comment by shairanshrawat** [comment]
![Screenshot (51)_LI](https://user-images.githubusercontent.com/62132905/110837377-26716300-82c7-11eb-920e-a4f3a77e555f.jpg)

Sir I'm talking about this question area. I will be working on designing it in a better perspective as I mention above

**Comment by shrey27tri01** [comment]
@shairanshrawat I think there's a little confusion here: the area you are talking about contains the tip of the day, and we don't need further revamps in it's design :smile: 
However, if you have any other ideas for the homepage or for the tip of the day, you are most welcome to work on those!
