### ISSUE TITLE
Update READMe.md

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy.github.io#91]
I would like to add contributing.md file . I will contribute by putting steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forked repo as well as local repo as the changes are made to the upstream
This will make this file a one stop for contributions

I would like to work on this as a part of GSSOC'21

**Comment by sairish2001** [comment]
Go ahead!
Actually it's already there in the ReadMe file. But if you can make it more clear for beginners then you can make changes in ReadMe.md

**Comment by khareyash05** [comment]
Okay Thanx

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any

Deadline 13 March,2021 (11:59 PM IST)
