### ISSUE TITLE
No space between the mic button and the search button.

### ISSUE THREAD

**Issue by vmk8826** [sairish2001/makesmatheasy.github.io#92]
## **Describe the bug**

- No space between the mic button and the search button.

## **Possible solution**

- There should be some amount of space between the mic and the search button.

## **Screenshots**

![bug](https://user-images.githubusercontent.com/68069180/110749759-8a643f00-8267-11eb-88e8-d6c6baef1a0a.jpg)

**Comment by vmk8826** [comment]
Can you assign it to me, I am a GSoC 2021 aspirant.

**Comment by sairish2001** [comment]
One of our participant is making some new changes in this search bar.So, wait for the PR

**Comment by vmk8826** [comment]
okay

**Comment by sairish2001** [comment]
[#44](https://github.com/sairish2001/makesmatheasy.github.io/issues/44)
