### ISSUE TITLE
Changing the C (clear) button functioning, it is not clearing the all the fields 

### ISSUE THREAD

**Issue by SanskrutiRP** [sairish2001/makesmatheasy.github.io#93]
In the calculator design we have to click on clear button to clear the input field.
And click on backspace button to clear the output field.
Which is creating problem for first time using user.
Would like to make changes to that?
Please assign this issue to me.
Thank You!!!

**Comment by SanskrutiRP** [comment]
I am GSSoC'21 participant. Please assign this to me.

**Comment by sairish2001** [comment]
Yeah! I was thinking off the same problem, you catch it right.

Can you make backspace button to work as clear button also, i.e if pressed long for 2 seconds then it must clear fields, otherwise serve a backspace functionality.

**Comment by SanskrutiRP** [comment]
Yup I can, thank you!
Can you add GSSoC'21 label to it?

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 15 March,2021 (11:59 PM IST)

**Comment by SanskrutiRP** [comment]
> Feel free to ask your doubts, if any
> Deadline 15 March,2021 (11:59 PM IST)

Thank You!!!

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by SanskrutiRP** [comment]
Hey @sairish2001 , I am done with this but I think it will be efficient if it clears when pressed for 1 sec. 
What do you think?

**Comment by sairish2001** [comment]
yes! fine

**Comment by SanskrutiRP** [comment]
Okay!!
