### ISSUE TITLE
Trigonometry Values favorite button fix.

### ISSUE THREAD

**Issue by aashishah** [sairish2001/makesmatheasy.github.io#96]
## **Describe the bug**

Upon clicking the Trigonometry Values button, the P/B/H favorite button gets activated instead of the Trigonometry Values option. Although it shows up in the footer, it doesn't seem to activate the "heart"/favorite button.

## **Possible solution**

This is a simple bug fix in either the JS or the CSS script.

## **Screenshots**
![Issue](https://user-images.githubusercontent.com/49470807/110758915-0e6ff400-8273-11eb-8bae-3ab7ed3ca46a.PNG)

**Comment by aashishah** [comment]
I'd like to fix this issue under GSSOC'21, thank you!

**Comment by sairish2001** [comment]
![Untitled](https://user-images.githubusercontent.com/60106112/110778323-36b61d80-8288-11eb-9826-74ce97ad888e.png)

Here's the problem in index.html file

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 13 March,2021 (11:59 PM IST)
